const m3uHeader = '#EXTM3U';

const int id3v1GenreLowerLimit = 0;
const int id3v1GenreUpperLimit = 191;
const List<String> id3v1GenreList = [
  'Blues',
  'Classic Rock',
  'Country',
  'Dance',
  'Disco',
  'Funk',
  'Grunge',
  'Hip-Hop',
  'Jazz',
  'Metal',
  'New Age',
  'Oldies',
  'Other',
  'Pop',
  'R&B',
  'Rap',
  'Reggae',
  'Rock',
  'Techno',
  'Industrial',
  'Alternative',
  'Ska',
  'Death Metal',
  'Pranks',
  'Soundtrack',
  'Euro-Techno',
  'Ambient',
  'Trip-Hop',
  'Vocal',
  'Jazz+Funk',
  'Fusion',
  'Trance',
  'Classical',
  'Instrumental',
  'Acid',
  'House',
  'Game',
  'Sound Clip',
  'Gospel',
  'Noise',
  'AlternRock',
  'Bass',
  'Soul',
  'Punk',
  'Space',
  'Meditative',
  'Instrumental Pop',
  'Instrumental Rock',
  'Ethnic',
  'Gothic',
  'Darkwave',
  'Techno-Industrial',
  'Electronic',
  'Pop-Folk',
  'Eurodance',
  'Dream',
  'Southern Rock',
  'Comedy',
  'Cult',
  'Gangsta Rap',
  'Top 40',
  'Christian Rap',
  'Pop / Funk',
  'Jungle',
  'Native American',
  'Cabaret',
  'New Wave',
  'Psychedelic',
  'Rave',
  'Showtunes',
  'Trailer',
  'Lo-Fi',
  'Tribal',
  'Acid Punk',
  'Acid Jazz',
  'Polka',
  'Retro',
  'Musical',
  'Rock & Roll',
  'Hard Rock',
  'Folk',
  'Folk-Rock',
  'National Folk',
  'Swing',
  'Fast Fusion',
  'Bebob',
  'Latin',
  'Revival',
  'Celtic',
  'Bluegrass',
  'Avantgarde',
  'Gothic Rock',
  'Progressive Rock',
  'Psychedelic Rock',
  'Symphonic Rock',
  'Slow Rock',
  'Big Band',
  'Chorus',
  'Easy Listening',
  'Acoustic',
  'Humour',
  'Speech',
  'Chanson',
  'Opera',
  'Chamber Music',
  'Sonata',
  'Symphony',
  'Booty Bass',
  'Primus',
  'Porn Groove',
  'Satire',
  'Slow Jam',
  'Club',
  'Tango',
  'Samba',
  'Folklore',
  'Ballad',
  'Power Ballad',
  'Rhythmic Soul',
  'Freestyle',
  'Duet',
  'Punk Rock',
  'Drum Solo',
  'A Cappella',
  'Euro-House',
  'Dance Hall',
  'Goa',
  'Drum & Bass',
  'Club-House',
  'Hardcore',
  'Terror',
  'Indie',
  'BritPop',
  'Negerpunk',
  'Polsk Punk',
  'Beat',
  'Christian Gangsta Rap',
  'Heavy Metal',
  'Black Metal',
  'Crossover',
  'Contemporary Christian',
  'Christian Rock',
  'Merengue',
  'Salsa',
  'Thrash Metal',
  'Anime',
  'JPop',
  'Synthpop',
  'Abstract',
  'Art Rock',
  'Baroque',
  'Bhangra',
  'Big Beat',
  'Breakbeat',
  'Chillout',
  'Downtempo',
  'Dub',
  'EBM',
  'Eclectic',
  'Electro',
  'Electroclash',
  'Emo',
  'Experimental',
  'Garage',
  'Global',
  'IDM',
  'Illbient',
  'Industro-Goth',
  'Jam Band',
  'Krautrock',
  'Leftfield',
  'Lounge',
  'Math Rock',
  'New Romantic',
  'Nu-Breakz',
  'Post-Punk',
  'Post-Rock',
  'Psytrance',
  'Shoegaze',
  'Space Rock',
  'Trop Rock',
  'World Music',
  'Neoclassical',
  'Audiobook',
  'Audio Theatre',
  'Neue Deutsche Welle',
  'Podcast',
  'Indie Rock',
  'G-Funk',
  'Dubstep',
  'Garage Rock',
  'Psybient',
];

const String APP_MSG_PREFIX = 'MUSIC_PLAYER';
const int MUSIC_ITEMS_PARTITION = 60;

const Map<String, String> colorMap = {
  'black': '\x1B[30m',
  'red': '\x1B[31m',
  'green': '\x1B[32m',
  'yellow': '\x1B[33m',
  'blue': '\x1B[34m',
  'magenta': '\x1B[35m',
  'cyan': '\x1B[36m',
  'white': '\x1B[37m',
  'reset': '\x1B[0m',
  '': '',
};

const int queueSectionIdx = -1;

